/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AnswerCard: typeof import('./src/components/learning/AnswerCard.vue')['default']
    AppHeader: typeof import('./src/components/layout/AppHeader.vue')['default']
    FeedbackButtons: typeof import('./src/components/learning/FeedbackButtons.vue')['default']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    ProgressBar: typeof import('./src/components/learning/ProgressBar.vue')['default']
    QuestionCard: typeof import('./src/components/learning/QuestionCard.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    VanButton: typeof import('vant/es')['Button']
    VanCellGroup: typeof import('vant/es')['CellGroup']
    VanField: typeof import('vant/es')['Field']
    VanForm: typeof import('vant/es')['Form']
    VanLoading: typeof import('vant/es')['Loading']
  }
}
